<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		// redirection vers les pages home, about et 404
			if(isset($route) && $route === 'home') {
			    require 'template/home.phtml';
			    
			} else if (isset($route) && $route === 'about') {
			    require 'templates/about.phtml';
			    
			} else {
			    require 'templates.404.phtml';
			}
		?>
	</body>
</html>